### ISSUE TITLE
Control Screen

### ISSUE THREAD

**Issue by hubert-farnsworth** [bprollinson/robotzombieninjawizard#2]
Hi @bprollinson, nice work on the game. just a suggestion, menu screens and/or an updated readme to include the control scheme, and symbol definitions would be beneficial since they differ from standard nethack.

**Comment by bprollinson** [comment]
@hubert-farnsworth Thanks for your feedback. I will definitely look at doing that soon. I started this game for my own enjoyment and honestly never thought anyone would take interest in it.

**Comment by bprollinson** [comment]
@hubert-farnsworth Just added in-game instructions and also a README.md with enough details to get players started. Let me know if you have any other feedback.
